language: php

sudo: false

notifications:
  email:
    on_success: never

cache:
  directories:
    - $HOME/.composer/cache

php:
  - 7.0
  - 7.1
  - 7.2
  - 7.3
  - 7.4
  - 8.0

env:
  - TESTBENCH=3.0.* PHPUNIT=~4.8.36
  - TESTBENCH=3.1.* PHPUNIT=~5.7.21
  - TESTBENCH=3.2.* PHPUNIT=~5.7.21
  - TESTBENCH=3.3.* PHPUNIT=~5.7.21
  - TESTBENCH=3.4.* PHPUNIT=~5.7.21
  - TESTBENCH=3.5.* PHPUNIT=~6.0
  - TESTBENCH=3.6.* PHPUNIT=^7.0
  - TESTBENCH=3.7.* PHPUNIT=^7.0
  - TESTBENCH=3.8.* PHPUNIT=^7.5
  - TESTBENCH=^4.0  PHPUNIT=^8.0

matrix:
  exclude:
    - php: 7.0
      env: TESTBENCH=3.6.* PHPUNIT=^7.0
    - php: 7.0
      env: TESTBENCH=3.7.* PHPUNIT=^7.0
    - php: 7.0
      env: TESTBENCH=3.8.* PHPUNIT=^7.5
    - php: 7.0
      env: TESTBENCH=^4.0  PHPUNIT=^8.0
    - php: 7.1
      env: TESTBENCH=^4.0  PHPUNIT=^8.0
    - php: 7.2
      env: TESTBENCH=3.0.* PHPUNIT=~4.8.36
    - php: 7.3
      env: TESTBENCH=3.0.* PHPUNIT=~4.8.36
    - php: 7.4
      env: TESTBENCH=3.0.* PHPUNIT=~4.8.36
  include:
    - php: 7.3
      env: TLD_DB_TEST=1
      before_install: 'true'
      install: php build/build.php
      script: git diff --exit-code
      after_success: 'true'

before_install:
  - composer validate --strict
  - composer require orchestra/testbench:$TESTBENCH phpunit/phpunit:$PHPUNIT --no-update --no-interaction --dev

install:
  - travis_retry composer update --no-suggest --no-interaction
  - composer info

script:
  - vendor/bin/phpunit --coverage-clover=coverage.xml

after_success:
    - bash <(curl -s https://codecov.io/bash)
